manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/ftc/zmk
  projects:
    - name: tree
      remote: zmkfirmware
      revision: mouse-ftc
      import: app/west.yml
  self:
    path: config
